"""High-level Goodboy build pipeline."""

from __future__ import annotations

import shutil
from pathlib import Path

from .atlas import compose_atlas, make_contact_sheet, render_animation_previews, validate_atlas
from .jsonio import read_json, write_json
from .project import init_project, load_project, save_project
from .qa import audit_frames, evaluate_qa_policy, make_centering_overlay, make_white_edge_preview, write_qa_report
from .raster import build_frames_from_row_strips
from .safety import find_suspicious_renderer_scripts
from .schemas import RunSummary


def build_from_row_strips(
    *,
    project_dir: Path,
    rows_dir: Path,
    run_id: str,
    pet_id: str | None = None,
    display_name: str | None = None,
    install: bool = False,
    install_root: Path | None = None,
    install_override_reason: str | None = None,
    row_provenance: str | None = None,
    visual_approval: str | None = None,
    force: bool = True,
) -> RunSummary:
    if not (project_dir / "goodboy.json").exists():
        if pet_id is None or display_name is None:
            raise ValueError("pet_id and display_name are required when initializing a new project")
        project = init_project(project_dir, pet_id=pet_id, display_name=display_name)
    else:
        project = load_project(project_dir)
        if pet_id is not None:
            project.id = pet_id
        if display_name is not None:
            project.display_name = display_name

    run_dir = project_dir / "runs" / run_id
    transparent_dir = run_dir / "transparent-strips"
    frames_root = run_dir / "frames"
    final_dir = run_dir / "final"
    qa_dir = run_dir / "qa"
    package_dir = run_dir / "package"

    build_frames_from_row_strips(
        source_dir=rows_dir,
        transparent_dir=transparent_dir,
        frames_root=frames_root,
        force=force,
    )
    compose_atlas(
        frames_root,
        output_png=final_dir / "spritesheet.png",
        output_webp=final_dir / "spritesheet.webp",
    )
    validation = validate_atlas(final_dir / "spritesheet.webp")
    write_json(final_dir / "validation.json", validation.to_dict())
    make_contact_sheet(final_dir / "spritesheet.webp", qa_dir / "contact-sheet.png")
    render_animation_previews(frames_root, qa_dir / "previews")
    make_white_edge_preview(frames_root, qa_dir / "edge-preview-white.png")
    make_centering_overlay(frames_root, qa_dir / "centering-overlay.png")
    centering_report_path = frames_root / "centering-report.json"
    if centering_report_path.is_file():
        write_json(qa_dir / "centering-report.json", read_json(centering_report_path))
    qa_report = audit_frames(frames_root)
    qa_policy = evaluate_qa_policy(
        validation,
        qa_report,
        override_reason=install_override_reason,
        install_requested=install,
        row_provenance=row_provenance,
        visual_approval=visual_approval,
    )
    write_qa_report(qa_dir / "duplicate-audit.json", qa_report)
    write_json(qa_dir / "install-policy.json", qa_policy.to_dict())
    write_json(
        qa_dir / "review.json",
        {
            "ok": validation.ok and qa_report.ok,
            "errors": validation.errors + qa_report.errors,
            "warnings": validation.warnings + qa_report.warnings,
            "install_policy": qa_policy.to_dict(),
        },
    )
    write_json(qa_dir / "human-review-checklist.json", human_review_checklist(run_id))

    package_dir.mkdir(parents=True, exist_ok=True)
    shutil.copy2(final_dir / "spritesheet.webp", package_dir / "spritesheet.webp")
    write_json(
        package_dir / "pet.json",
        {
            "id": project.id,
            "displayName": project.display_name,
            "description": f"{project.display_name} Codex pet generated by Goodboy.",
            "spritesheetPath": "spritesheet.webp",
        },
    )

    summary = RunSummary(
        ok=validation.ok and qa_report.ok,
        version=run_id,
        source_rows=str(rows_dir),
        spritesheet=str(final_dir / "spritesheet.webp"),
        contact_sheet=str(qa_dir / "contact-sheet.png"),
        edge_preview=str(qa_dir / "edge-preview-white.png"),
        validation=str(final_dir / "validation.json"),
        review=str(qa_dir / "review.json"),
        duplicate_audit=str(qa_dir / "duplicate-audit.json"),
        package_dir=str(package_dir),
    )
    write_json(run_dir / "run-summary.json", summary.to_dict())

    project.active_run_id = run_id
    save_project(project_dir, project)

    if install:
        if not qa_policy.ok_to_install:
            details = "; ".join(qa_policy.hard_failures) or "unknown QA policy failure"
            raise ValueError(
                f"QA policy blocks install: {details}"
            )
        suspicious = find_suspicious_renderer_scripts(project_dir)
        if suspicious:
            raise ValueError(f"suspicious renderer scripts block install: {', '.join(suspicious)}")
        install_package(package_dir=package_dir, pet_id=project.id, install_root=install_root)
    return summary


def human_review_checklist(run_id: str) -> dict[str, object]:
    return {
        "run_id": run_id,
        "required_before_approval": [
            "Open qa/contact-sheet.png and confirm every state is recognizable.",
            "Open qa/previews/*.gif and confirm loops do not drift, clip, or duplicate unnaturally.",
            "Open qa/edge-preview-white.png and confirm there is no visible green halo.",
            "Open qa/centering-overlay.png and confirm frame centers are stable enough for idle/waiting/review.",
            "Read qa/review.json and qa/install-policy.json; approve only if hard failures are absent or intentionally overridden.",
            "Confirm the character identity, style preset, and any user/AI critique overrides are reflected in the row art.",
        ],
        "approval_command": "goodboy approve <project-dir> --notes \"User approved contact sheet, previews, edge, centering, identity, and style\"",
    }


def install_package(*, package_dir: Path, pet_id: str, install_root: Path | None = None) -> Path:
    install_root = install_root or Path.home() / ".codex" / "pets"
    target = install_root / pet_id
    archive_existing_install(target)
    target.mkdir(parents=True, exist_ok=True)
    shutil.copy2(package_dir / "pet.json", target / "pet.json")
    shutil.copy2(package_dir / "spritesheet.webp", target / "spritesheet.webp")
    return target


def archive_existing_install(target: Path) -> None:
    if not target.exists():
        return
    archive_root = target.parent / ".goodboy-archives" / target.name
    archive_root.mkdir(parents=True, exist_ok=True)
    index = 1
    while True:
        archive_dir = archive_root / f"archive-{index:03d}"
        if not archive_dir.exists():
            break
        index += 1
    archive_dir.mkdir(parents=True)
    for filename in ("pet.json", "spritesheet.webp"):
        source = target / filename
        if source.exists():
            shutil.copy2(source, archive_dir / filename)
